import fonts from './fonts';

export default {
  fontFamily: fonts.fontFamily,
  fontSize: Number(fonts.defaultSize.replace('px', '')),
  fontWeightLight: fonts.light,
  fontWeightRegular: fonts.regular,
  fontWeightMedium: fonts.semibold,
  fontWeightBold: fonts.bold,
  h1: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.header1Weight,
    fontSize: fonts.header1Size,
    lineHeight: fonts.header1LineHeight,
    letterSpacing: 'normal',
  },
  h2: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.header2Weight,
    fontSize: fonts.header2Size,
    lineHeight: fonts.header2LineHeight,
    letterSpacing: 'normal',
  },
  h3: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.header3Weight,
    fontSize: fonts.header3Size,
    lineHeight: fonts.header3LineHeight,
    letterSpacing: 'normal',
  },
  h4: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.header3Weight,
    fontSize: fonts.header3Size,
    lineHeight: fonts.header3LineHeight,
    letterSpacing: 'normal',
  },
  h5: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.header3Weight,
    fontSize: fonts.header3Size,
    lineHeight: fonts.header3LineHeight,
    letterSpacing: 'normal',
  },
  h6: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.header3Weight,
    fontSize: fonts.header3Size,
    lineHeight: fonts.header3LineHeight,
    letterSpacing: 'normal',
  },
  subtitle1: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.regular,
    fontSize: fonts.mediumTextSize,
    lineHeight: 1.3,
    letterSpacing: 'normal',
  },
  subtitle2: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.semibold,
    fontSize: fonts.smallTextSize,
    lineHeight: 1.3,
    letterSpacing: 'normal',
  },
  body1: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.regular,
    fontSize: fonts.smallTextSize,
    lineHeight: 1.7142,
    letterSpacing: 'normal',
  },
  body2: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.regular,
    fontSize: fonts.smallTextSize,
    lineHeight: 1.3,
    letterSpacing: 'normal',
  },
  button: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.semibold,
    fontSize: fonts.smallTextSize,
    lineHeight: 1.3,
    letterSpacing: 'normal',
    textTransform: 'none',
  },
  caption: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.regular,
    fontSize: fonts.extraSmallTextSize,
    lineHeight: 1.3,
    letterSpacing: 'normal',
  },
  overline: {
    fontFamily: fonts.fontFamily,
    fontWeight: fonts.regular,
    fontSize: fonts.extraSmallTextSize,
    lineHeight: 2.3,
    letterSpacing: 'normal',
    textTransform: 'uppercase',
  },
};
