/* eslint-disable no-underscore-dangle */
// This file was autogenerated, do not modify.
import primitive from './primitive';

const alias = {
  color: {
    text: {
      primary: primitive.color.gray800,
      secondary: primitive.color.gray200,
      error: primitive.color.red900,
      inverted: primitive.color.gray10,
      disabled: primitive.color.gray50,
      tertiary: primitive.color.gray50,
    },
    background: {
      primary: primitive.color.grayWhite,
      secondary: primitive.color.gray10,
      inverted: primitive.color.gray900,
      info: primitive.color.blue100,
      success: primitive.color.green100,
      error: primitive.color.red100,
      warning: primitive.color.yellow100,
      disabled: primitive.color.gray15,
      hover: primitive.color.gray15,
      selected: primitive.color.gray20,
      secondaryHover: primitive.color.gray15,
      secondarySelected: primitive.color.gray20,
      invertedHover: primitive.color.gray300,
      invertedSelected: primitive.color.gray400,
    },
    border: {
      secondary: primitive.color.gray20,
      info: primitive.color.blue900,
      error: primitive.color.red900,
      warning: primitive.color.yellow900,
      success: primitive.color.green900,
      disabled: primitive.color.gray50,
      primary: primitive.color.gray800,
      focus: primitive.color.grayWhite,
      selectedHover: primitive.color.gray300,
      secondaryHover: primitive.color.gray800,
      secondarySelected: primitive.color.gray800,
    },
    element: {
      secondary: primitive.color.gray100,
      primary: primitive.color.gray800,
      info: primitive.color.blue900,
      success: primitive.color.green900,
      error: primitive.color.red900,
      warning: primitive.color.yellow900,
      inverted: primitive.color.gray10,
      disabled: primitive.color.gray50,
      secondaryHover: primitive.color.gray800,
      secondarySelected: primitive.color.gray400,
    },
    scrim: {
      heavy: primitive.color.grayWhite,
      light100: primitive.color.grayWhite,
      light60: primitive.color.grayWhite,
      light30: primitive.color.grayWhite,
    },
  },
  borderRadius: {
    small: primitive.borderRadius._400,
    medium: primitive.borderRadius._800,
    large: primitive.borderRadius._1600,
    circle: primitive.borderRadius.circle,
  },
};

export default { alias, primitive };
