/* eslint-disable no-underscore-dangle */
// This file was autogenerated, do not modify.
import primitive from './primitive';

const alias = {
  color: {
    text: {
      primary: primitive.color.gray10,
      secondary: primitive.color.gray30,
      error: primitive.color.red900,
      inverted: primitive.color.gray800,
      disabled: primitive.color.gray100,
      tertiary: primitive.color.gray50,
    },
    background: {
      primary: primitive.color.gray800,
      secondary: primitive.color.gray700,
      primaryInverted: primitive.color.grayWhite,
      info: primitive.color.blue100,
      success: primitive.color.green100,
      error: primitive.color.red100,
      warning: primitive.color.yellow100,
      disabled: primitive.color.gray200,
      primaryHover: primitive.color.gray500,
      primarySelected: primitive.color.gray300,
      secondaryHover: primitive.color.gray500,
      secondarySelected: primitive.color.gray300,
      primaryInvertedHover: primitive.color.gray40,
      primaryInvertedSelected: primitive.color.gray50,
    },
    border: {
      secondary: primitive.color.gray400,
      info: primitive.color.blue900,
      error: primitive.color.red900,
      warning: primitive.color.yellow900,
      success: primitive.color.green900,
      disabled: primitive.color.gray100,
      primary: primitive.color.gray10,
      focus: primitive.color.grayWhite,
      primarySelectedHover: primitive.color.gray40,
      secondaryHover: primitive.color.gray10,
      secondarySelected: primitive.color.gray50,
    },
    element: {
      secondary: primitive.color.gray30,
      primary: primitive.color.gray10,
      info: primitive.color.blue900,
      success: primitive.color.green900,
      error: primitive.color.red900,
      warning: primitive.color.yellow900,
      primaryInverted: primitive.color.gray800,
      disabled: primitive.color.gray100,
      secondaryHover: primitive.color.gray10,
      secondarySelected: primitive.color.gray50,
    },
  },
  borderRadius: {
    small: primitive.borderRadius._400,
    medium: primitive.borderRadius._800,
    large: primitive.borderRadius._1600,
    circle: primitive.borderRadius.circle,
  },
};

export default { alias, primitive };
