/* eslint-disable no-underscore-dangle */
// This file was autogenerated, do not modify.
import primitive from './primitive';

const alias = {
  color: {
    text: {
      primary: primitive.color.grayBlack,
      secondary: primitive.color.gray300,
      error: primitive.color.red900,
      inverted: primitive.color.grayWhite,
      disabled: primitive.color.gray50,
      tertiary: primitive.color.gray50,
    },
    background: {
      primary: primitive.color.grayWhite,
      secondary: primitive.color.gray10,
      inverted: primitive.color.blueA200,
      info: primitive.color.blue100,
      success: primitive.color.green100,
      error: primitive.color.red100,
      warning: primitive.color.yellow100,
      disabled: primitive.color.gray30,
      hover: primitive.color.blue50,
      selected: primitive.color.blueA100,
      secondaryHover: primitive.color.blue50,
      secondarySelected: primitive.color.blueA200,
      invertedHover: primitive.color.blueA300,
      invertedSelected: primitive.color.blueA200,
    },
    border: {
      secondary: primitive.color.gray30,
      info: primitive.color.blue900,
      error: primitive.color.red900,
      warning: primitive.color.yellow900,
      success: primitive.color.green900,
      disabled: primitive.color.gray50,
      primary: primitive.color.blueA200,
      focus: primitive.color.grayWhite,
      selectedHover: primitive.color.blueA300,
      secondaryHover: primitive.color.blueA300,
      secondarySelected: primitive.color.blueA300,
    },
    element: {
      secondary: primitive.color.blueA200,
      primary: primitive.color.grayBlack,
      info: primitive.color.blue900,
      success: primitive.color.green900,
      error: primitive.color.red900,
      warning: primitive.color.yellow900,
      inverted: primitive.color.grayWhite,
      disabled: primitive.color.gray50,
      secondaryHover: primitive.color.blueA300,
      secondarySelected: primitive.color.blueA400,
    },
    scrim: {
      heavy: primitive.color.grayWhite,
      light100: primitive.color.grayWhite,
      light60: primitive.color.grayWhite,
      light30: primitive.color.grayWhite,
    },
  },
  borderRadius: {
    small: primitive.borderRadius._400,
    medium: primitive.borderRadius._800,
    large: primitive.borderRadius._4800,
    circle: primitive.borderRadius.circle,
  },
};

export default { alias, primitive };
